### PR TITLE
Increase ticker max length to 9

### PR DESCRIPTION
**Pull request by kodemill**

### CODE REVIEW

**Comment by Quantumplation** [comment]
Justification for this PR: This is in preparation for registering the SUNDAE token metadata;

There's not a great abbreviation for SUNDAE, and we have already built up expectations around the token being named SUNDAE; changing it at the 11th hour would create significant confusion and create fertile soil for scammers.

**Review by disassembler — APPROVED** [review]
I fully support this. I thought the limitation of 5 was annoying myself as my personal token I minted (and hasn't been added to registry yet because of this same issue) is DISASM.

**Comment by Quantumplation** [comment]
Some evidence for distribution of token tickers in the wild on other chains:

https://ethereum.stackexchange.com/questions/25619/is-there-length-limits-on-token-symbols

**Comment by piotr-iohk** [comment]
Thanks! Can we also make corresponding update in [README](https://github.com/input-output-hk/offchain-metadata-tools/tree/master/token-metadata-creator#add-optional-fields).

Additional test in [here](https://github.com/input-output-hk/offchain-metadata-tools/tree/master/token-metadata-creator/test) would be handy too. :sweat_smile:

I don't know if this is enough or is there a need to do a change also elsewhere in this repo, but maybe not... :thinking: 
@rvl @sevanspowell.
 
I think we need the same change in cardano-wallet as there seems to be the same constraint there :man_shrugging:

**Comment by rvl** [comment]
Perhaps we should increase the max length to 9 so that the MILKSHAKE ticker is also possible?

**Review by rvl — APPROVED** [review]

**Comment by Quantumplation** [comment]
@piotr-iohk Would you like me to bump the max length to 9, as suggested by rvl?

**Comment by piotr-iohk** [comment]
>Would you like me to bump the max length to 9, as suggested by rvl?

I don't have strong opinion. I'm fine with 9.

**Comment by Quantumplation** [comment]
@piotr-iohk feedback addressed :) I wasn't 100% able to confirm the test locally, as I couldn't get it to run the newly built version of the code, it kept falling back to the version at 5 characters, but it seemed straightforward enough.

**Comment by rvl** [comment]
@Quantumplation Would you also be able to raise a PR on [CIP-26](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0026). There was no particular reason for choosing max length 5 - only that there should be some limit, and the ticker is meant to be a _short_ identifier which abbreviates the token name. For example, the max ticker length on NASDAQ is 5, and MSFT is the ticker for Microsoft. If token creators choose long tickers, they may get truncated in GUIs.

**Review by rvl — APPROVED** [review]

**Review by sevanspowell — APPROVED** [review]

**Comment by Quantumplation** [comment]
Will do :)

**Comment by Quantumplation** [comment]
Took me a little while @rvl, but here you go: https://github.com/cardano-foundation/CIPs/pull/207

**Pull request merged**
