### PR TITLE
Fix metadata desynchronization

### PR DESCRIPTION
**Pull request by sevanspowell**
- Adds a script that queries the GH repository and sets the state of
metadata database to match.
- Add NixOS service.
- Add integration tests that check that the write part of the script
writes correctly, and doesn't touch the database at all if an
exception occurs.

### CODE REVIEW

**Review by rvl — COMMENTED** [review]
So this is a script to slurp all the metadata json files from a registry git repo into the database?

**Comment by sevanspowell** [comment]
Yep. And it exists because the webhook is flaky. A number of times a PR has been merged, a notification has been sent to the webhook, but then the webhook fails to retrieve the metadata entry from GitHub (usually it seems unable to reach the github API, but the reasons have varied). This leaves the Postgres database in a different state to the repo.

This script is just a quick fix to that problem, because we don't have the time to dedicate to a proper solution.

**Comment by rvl** [comment]
OK fair enough.

**Review by rvl — APPROVED** [review]
:ship:

**Pull request merged**
